/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : bigint,
  'customerName' : string,
  'status' : BookingStatus,
  'driverId' : bigint,
  'destination' : string,
  'customerPhone' : string,
  'date' : bigint,
  'createdAt' : bigint,
  'createdBy' : Principal,
  'time' : string,
  'durationHours' : bigint,
  'pickupAddress' : string,
  'totalPrice' : bigint,
}
export type BookingStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'confirmed' : null };
export interface DriveEaseInfo {
  'drivers' : Array<Driver>,
  'adminId' : Principal,
}
export interface Driver {
  'id' : bigint,
  'name' : string,
  'languages' : Array<string>,
  'pricePerHour' : bigint,
  'description' : string,
  'available' : boolean,
  'experienceYears' : bigint,
  'rating' : number,
  'photo' : string,
}
export interface UserProfile { 'name' : string, 'phone' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDriver' : ActorMethod<
    [string, string, bigint, Array<string>, number, bigint, string],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBooking' : ActorMethod<
    [string, string, string, string, bigint, string, bigint, bigint],
    bigint
  >,
  'deleteDriver' : ActorMethod<[bigint], undefined>,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getAvailableDrivers' : ActorMethod<[], Array<Driver>>,
  'getBooking' : ActorMethod<[bigint], [] | [Booking]>,
  'getBookingsByPhone' : ActorMethod<[string], Array<Booking>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDriver' : ActorMethod<[bigint], [] | [Driver]>,
  'getDrivers' : ActorMethod<[], Array<Driver>>,
  'getInfo' : ActorMethod<[], DriveEaseInfo>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedDrivers' : ActorMethod<[], undefined>,
  'updateBookingStatus' : ActorMethod<[bigint, BookingStatus], undefined>,
  'updateDriverAvailability' : ActorMethod<[bigint, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];