/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BookingStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : BookingStatus,
  'driverId' : IDL.Nat,
  'destination' : IDL.Text,
  'customerPhone' : IDL.Text,
  'date' : IDL.Int,
  'createdAt' : IDL.Int,
  'createdBy' : IDL.Principal,
  'time' : IDL.Text,
  'durationHours' : IDL.Nat,
  'pickupAddress' : IDL.Text,
  'totalPrice' : IDL.Nat,
});
export const Driver = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'languages' : IDL.Vec(IDL.Text),
  'pricePerHour' : IDL.Nat,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'experienceYears' : IDL.Nat,
  'rating' : IDL.Float64,
  'photo' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'phone' : IDL.Text,
});
export const DriveEaseInfo = IDL.Record({
  'drivers' : IDL.Vec(Driver),
  'adminId' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDriver' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Vec(IDL.Text),
        IDL.Float64,
        IDL.Nat,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBooking' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Int,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
      ],
      [IDL.Nat],
      [],
    ),
  'deleteDriver' : IDL.Func([IDL.Nat], [], []),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getAvailableDrivers' : IDL.Func([], [IDL.Vec(Driver)], ['query']),
  'getBooking' : IDL.Func([IDL.Nat], [IDL.Opt(Booking)], ['query']),
  'getBookingsByPhone' : IDL.Func([IDL.Text], [IDL.Vec(Booking)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDriver' : IDL.Func([IDL.Nat], [IDL.Opt(Driver)], ['query']),
  'getDrivers' : IDL.Func([], [IDL.Vec(Driver)], ['query']),
  'getInfo' : IDL.Func([], [DriveEaseInfo], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedDrivers' : IDL.Func([], [], []),
  'updateBookingStatus' : IDL.Func([IDL.Nat, BookingStatus], [], []),
  'updateDriverAvailability' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BookingStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : BookingStatus,
    'driverId' : IDL.Nat,
    'destination' : IDL.Text,
    'customerPhone' : IDL.Text,
    'date' : IDL.Int,
    'createdAt' : IDL.Int,
    'createdBy' : IDL.Principal,
    'time' : IDL.Text,
    'durationHours' : IDL.Nat,
    'pickupAddress' : IDL.Text,
    'totalPrice' : IDL.Nat,
  });
  const Driver = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'languages' : IDL.Vec(IDL.Text),
    'pricePerHour' : IDL.Nat,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'experienceYears' : IDL.Nat,
    'rating' : IDL.Float64,
    'photo' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'phone' : IDL.Text });
  const DriveEaseInfo = IDL.Record({
    'drivers' : IDL.Vec(Driver),
    'adminId' : IDL.Principal,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDriver' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Vec(IDL.Text),
          IDL.Float64,
          IDL.Nat,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBooking' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Int,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
        ],
        [IDL.Nat],
        [],
      ),
    'deleteDriver' : IDL.Func([IDL.Nat], [], []),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getAvailableDrivers' : IDL.Func([], [IDL.Vec(Driver)], ['query']),
    'getBooking' : IDL.Func([IDL.Nat], [IDL.Opt(Booking)], ['query']),
    'getBookingsByPhone' : IDL.Func([IDL.Text], [IDL.Vec(Booking)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDriver' : IDL.Func([IDL.Nat], [IDL.Opt(Driver)], ['query']),
    'getDrivers' : IDL.Func([], [IDL.Vec(Driver)], ['query']),
    'getInfo' : IDL.Func([], [DriveEaseInfo], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedDrivers' : IDL.Func([], [], []),
    'updateBookingStatus' : IDL.Func([IDL.Nat, BookingStatus], [], []),
    'updateDriverAvailability' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };